"""Add Operarion

Revision ID: c16c32268e19
Revises: 
Create Date: 2024-02-06 18:19:07.243553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16c32268e19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Surname', sa.String(), nullable=True),
    sa.Column('Birthday', sa.String(), nullable=False),
    sa.Column('Gender', sa.String(), nullable=True),
    sa.Column('Height', sa.Integer(), nullable=False),
    sa.Column('Weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_user')
    # ### end Alembic commands ###